### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by Dhruuva** [yoko0180/vue-cli-plugin-pug-template#1]
Hi !
I done standard installation Vue CLI v4.2.2
vue create my-vue

And after this vue add pug-template

When I do npm run serve 

I get this  
![pug_Template](https://user-images.githubusercontent.com/5820396/74131616-c3118f00-4bf5-11ea-97f8-317767a7c7f6.png)

_

> Failed to resolve loader: pug-plain-loader
> You may need to install it.

_

Why it is so pity looks ? 
Best regards.

**Comment by yoko0180** [comment]
sorry.
This plugin is just for inserting files using pug.
Set up your pug environment with the following command:

`vue add pug`
